method=overlay
layer=cutout
tiles=1-17
connectTiles=grass_block_top
tintIndex=0
tintBlock=grass_block
matchTiles=cobblestone mossy_cobblestone oak_log light_gray_terracotta chiseled_quartz_block stone sandstone glowstone sea_lantern terracotta oak_planks obsidian gravel dirt dark_prismarine dark_prismarine_slab bricks dirt_path_top brown_glazed_terracotta red_glazed_terracotta coarse_dirt red_sand prismarine stone_bricks mud acacia_planks birch_planks spruce_planks jungle_planks dark_oak_planks mangrove_planks cherry_planks bamboo_planks crimson_planks warped_planks moss_block
