method=repeat
matchBlocks=mangrove_planks mangrove_stairs mangrove_fence mangrove_fence_gate mangrove_button mangrove_slab mangrove_slab bell_floor
width=2
height=2
tiles=textures/block/mangrove_planks 2-4
