method=repeat
matchBlocks=pale_oak_planks pale_oak_stairs pale_oak_fence pale_oak_fence_gate pale_oak_button pale_oak_slab mangrove_slab bell_floor
width=2
height=2
tiles=textures/block/pale_oak_planks 2-4
