method=repeat
matchTiles=sandstone_top sandstone_bottom cut_sandstone_top cut_sandstone_bottom red_sandstone_top red_cut_sandstone_top red_sandstone_bottom
width=2
height=2
tiles=textures/block/sandstone_top 2-4
